version: '3.9'

services:
  app:
    container_name: golang_app
    build: .
    restart: on-failure
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - go-db
    volumes:
      - "D:/go-app:/go/src"

  db:
    container_name: db_mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3307:3306"
    networks:
      - go-db
    volumes:
      - "D:/mysql:/var/lib/mysql"

networks:
  go-db:
    driver: bridge